---
title: "virtual_pulldown_"
format: html
---

```{r}
library("tidyverse")
library("igraph")
library("msigdbr")
library("fgsea")
library("ggraph")


df <- read.csv("../results/03_pval_integration/integrated_sig01.csv")

seeds <- df |> 
  pull(groupID)
```

```{r}
load(file='/home/projects/22140/exercise7_ppi.Rdata')
```

```{r}
ppi_genes <- unique(c(ppi$from, ppi$to))

in_ppi <- df |>
filter(groupID %in% ppi_genes)
```

```{r}
top100 <- in_ppi |>
arrange(padj_edgington) |>
slice_head(n = 100) |>
pull(groupID)

seeds <- top100
```

```{r}
g <- graph_from_data_frame(ppi, directed = FALSE)
```

```{r}
seed_neighbors <- ego(
graph = g,
order = 1,
nodes = V(g)[name %in% seeds],
mode = "all"
)
sub_nodes_names <- unique(unlist(lapply(seed_neighbors, as_ids)))

g_sub <- induced_subgraph(g, vids = V(g)[name %in% sub_nodes_names])
```

```{r}
filter_virtual_pulldown <- function(subGraph, parentGraph, cutoff) {
  # require vertex attribute "names" in both graphs
  if (is.null(V(subGraph)$name) || is.null(V(parentGraph)$name))
    stop("Both graphs must have vertex 'name' attributes.")
  
  mode <- "all"
  
  vn <- V(subGraph)$name
  
  #Calcula en degree de los nodos del subgrafo tanto en la network global como en la interna
  deg_full     <- degree(parentGraph, v = vn, mode = mode)
  deg_internal <- degree(subGraph,            mode = mode)
  
  #Crea un df de los nodos del subgrafo con ambos degrees y el ratio como features
  res <- data.frame(
    node          = vn,
    deg_internal  = deg_internal,
    deg_full      = deg_full,
    frac_internal = ifelse(deg_full > 0, deg_internal / deg_full, NA_real_),
    stringsAsFactors = FALSE
  )
  
  #Se queda solo con los nodos que no tienen NA en el ratio y cuyo ratio es mayor al cutoff
  nodes_to_keep <- res$node[!is.na(res$frac_internal) & res$frac_internal >= cutoff]
  
  #Crea un subgrafo del anterior subgrafo con estos nodos filtrados
  filteredSubGraph <- induced_subgraph(subGraph, vids = V(subGraph)[name %in% nodes_to_keep])
  
  #Añade el ratio como node atribute del subgrafo en cuestion
  V(filteredSubGraph)$frac_internal <- res$frac_internal[match(V(filteredSubGraph)$name, res$node)]
  
  filteredSubGraph
}
```

```{r}
g_filtered_0.2 <- filter_virtual_pulldown(g_sub, g, cutoff = 0.1)
length(V(g_filtered_0.2))
length(E(g_filtered_0.2))
```

```{r}
V(g_filtered_0.2)$Seed <- ifelse(V(g_filtered_0.2)$name %in% seeds, "+", "-")

ggraph(g_filtered_0.2, layout = "fr") +
  geom_node_point(mapping = aes(color = Seed)) +
  geom_edge_link(alpha = 0.05) 
```

```{r}
clusters <- cluster_louvain(g_filtered_0.2, resolution = 0.2, weights = NULL)
sizes(clusters)
```

```{r}
clusters_vector <- membership(clusters)
```

```{r}
V(g_filtered_0.2)$cluster <- factor(clusters_vector)

#Plot de los clústers
ggraph(g_filtered_0.2, layout = "fr") +
  geom_node_point(mapping = aes(color = cluster)) +
  geom_edge_link(alpha = 0.05)
```

```{r}
clus_1 <- names(clusters_vector[clusters_vector == "1"])
clus_2 <- names(clusters_vector[clusters_vector == "2"])
clus_3 <- names(clusters_vector[clusters_vector == "3"])
clus_4 <- names(clusters_vector[clusters_vector == "4"])
clus_5 <- names(clusters_vector[clusters_vector == "5"])
clus_6 <- names(clusters_vector[clusters_vector == "6"])
```

```{r}
background <- V(g_filtered_0.2)$name

BP_df <- msigdbr(species = "human", category = "C5", subcategory = "BP")
BP_list <- split(BP_df$ensembl_gene, BP_df$gs_name)
```

```{r}
clus1_res <- fora(BP_list, clus_1, background)
clus1_res
```

```{r}
clus2_res <- fora(BP_list, clus_2, background)
clus2_res
```

```{r}
clus3_res <- fora(BP_list, clus_3, background)
clus3_res
```

```{r}
clus4_res <- fora(BP_list, clus_4, background)
clus4_res
```

```{r}
clus5_res <- fora(BP_list, clus_5, background)
clus5_res
```

```{r}
clus6_res <- fora(BP_list, clus_6, background)
clus6_res
```

```{r}
clus1_res <- clus1_res |> 
  mutate(logpadj = - log10(padj)) |> 
  head(10)


p165932 <- ggplot(clus1_res,
       aes(x = logpadj,
           y = reorder(pathway, logpadj),
           size = foldEnrichment,
           color = foldEnrichment)) +
  
  geom_point(alpha = 0.75) +
  
  scale_color_gradient(low = "#fca5a5", high = "#b91c1c") +

  geom_vline(xintercept = -log10(0.05),
             linetype = "dashed", color = "grey40") +

  labs(
    title = "Top Enriched Pathways in Cluster 1",
    x = "-log10(adjusted p-value)",
    y = "Pathway",
    size = "Fold Enrichemnt",
    color = "Fold Enrichemnt"
  ) +
  
  theme_minimal(base_size = 14) +
  theme(
    axis.text.y = element_text(size = 9, lineheight = 1.1),
    plot.title  = element_text(face = "bold", hjust = 0.5),
    legend.position = "right"
  )

p165932

ggsave("../figures/joint_pathways_integrated_clus1.png", p165932, 
       width = 12, height = 7, dpi = 300)
```

```{r}
all_significant_pathways_virtualpd <- bind_rows(clus1_res, clus2_res, clus3_res, clus4_res, clus5_res, clus6_res) |> 
  filter(padj < 0.05) |> 
  pull(pathway)
all_significant_pathways_virtualpd
```

```{r}
all_significant_pathways_gsea <- read_csv("../results/03_pval_integration/fgsea_integrated_BP_sig.csv") |> 
  pull(pathway)
```

```{r}
new_pathways <- setdiff(all_significant_pathways_virtualpd, all_significant_pathways_gsea)
```

```{r}
all_significant_pathways_virtualpd_df <- bind_rows(clus1_res, clus2_res, clus3_res, clus4_res, clus5_res, clus6_res) |> 
  filter(padj < 0.05)

all_significant_pathways_virtualpd_df <- all_significant_pathways_virtualpd_df |> 
  filter(pathway %in% new_pathways) |> 
  arrange(padj) |> 
  head(10) |> 
  mutate(logpadj = - log10(padj))
```

```{r}
p165932_new <- ggplot(all_significant_pathways_virtualpd_df,
       aes(x = logpadj,
           y = reorder(pathway, logpadj),
           size = foldEnrichment,
           color = foldEnrichment)) +
  
  geom_point(alpha = 0.75) +
  
  scale_color_gradient(low = "#fca5a5", high = "#b91c1c") +

  geom_vline(xintercept = -log10(0.05),
             linetype = "dashed", color = "grey40") +

  labs(
    title = "Top Joint-only Enriched Pathways in Cluster 1",
    x = "-log10(adjusted p-value)",
    y = "Pathway",
    size = "Fold Enrichemnt",
    color = "Fold Enrichemnt"
  ) +
  
  theme_minimal(base_size = 14) +
  theme(
    axis.text.y = element_text(size = 9, lineheight = 1.1),
    plot.title  = element_text(face = "bold", hjust = 0.5),
    legend.position = "right"
  )

ggsave("../figures/joint_pathways_integrated_new.png", p165932_new, 
       width = 12, height = 7, dpi = 300)

```

```{r}
g_clus1 <- induced_subgraph(g_filtered_0.2, vids = clus_1)
betweenness_clus1 <- betweenness(g_clus1, directed = FALSE, weights = NULL, normalized = TRUE)
betweenness_clus1
max_betweenness <- max(betweenness_clus1)
max_betweenness_gene <- names(betweenness_clus1[betweenness_clus1 == max_betweenness])
max_betweenness_gene

```

```{r}
df <- data.frame(k = degree(g_clus1), bc = betweenness(g_clus1, normalized = TRUE))

df |>
  mutate(gene_id = rownames(df)) |>
  filter(bc > 0.1) |>
  ggplot(aes(x = gene_id, y = k)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90))



```
